metric: COCO
num_classes: 1

TrainDataset:
  name: COCODataSet
  image_dir: train_fire
  anno_path: annotations/fire_train.json
  dataset_dir: dataset/firecoco
  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']
  allow_empty: true
  empty_ratio: 0.1

EvalDataset:
  name: COCODataSet
  image_dir: val_fire
  anno_path: annotations/fire_test.json
  dataset_dir: dataset/firecoco
  allow_empty: true

TestDataset:
  name: ImageFolder
  anno_path: annotations/fire_test.json # also support txt (like VOC's label_list.txt)
  dataset_dir: dataset/firecoco # if set, anno_path will be 'dataset_dir/anno_path'