metric: VOC
map_type: 11point
num_classes: 1

TrainDataset:
  name: VOCDataSet
  dataset_dir: dataset/fire
  anno_path: trainval.txt
  label_list: label_list.txt
  data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

EvalDataset:
  name: VOCDataSet
  dataset_dir: dataset/fire
  anno_path: test.txt
  label_list: label_list.txt
  data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

TestDataset:
  name: ImageFolder
  anno_path: dataset/fire/label_list.txt  #voc格式无法进行测试，infer.py必须要解析json
#  anno_path: annotations/instances_val2017.json # also support txt (like VOC's label_list.txt)
#  dataset_dir: dataset/fire # if set, anno_path will be 'dataset_dir/anno_path'